title: Bojkotta kriget
description: >-
  En lista över företag som inte bojkottar ryssland och genom sin försäljning underlättar rysslands kring i Ukraina

url: https://njetputin.se

theme: minima

# theme: jekyll-theme-cayman
# kramdown:
#   parse_block_html: true

collections:
  - companies
