title: Bojkotta kriget och företag som stödjer det!
subtitle: Something something something
description: >-
  Hej konsument! Nedan ser du en lista över företag som direkt eller indirekt Stödjer Rysslands anfallskrig i Ukraina. Detta genom att tex ha tillverkligen / fabriker / försäljning
   av produkter I Ryssland och därigenom genererar inkomster till Ryska staten. Pengar som oavkortet går till krigsekonomin. Du har en otroligt möjlighet att med några enkla alternativa val
   HJÄLPA Ukraina och MOTVERKA Rysland

theme: minima

url: https://nejputin.se

collections:
  - companies
